# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of nod
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BuildAndDeployToNeocities

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
      
    - run: npm install
    - run: npm run build
    - run: npm run export
    
    - name: Deploy to Neocities
  # You may pin to the exact commit or the version.
  # uses: bcomnes/deploy-to-neocities@36e9d756435b31a2c1e13270272dd2f3376bdad4
      uses: bcomnes/deploy-to-neocities@v1.1.9
      with:
    # Neocities API token for site to deploy to
        api_token: ${{secrets.NEOCITIES_API_TOKEN}}
    # Delete orphaned files on neocities that don't exist in distDir
        cleanup: true
    # Local folder to deploy to neocities
        dist_dir: out
